spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bachelor_harvest?useSSL=false
    username: root
    password: DEBUG
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

liquibase:
  enabled: false

logging:
  file: build-log
