spring:
  datasource:
    url: jdbc:mysql://localhost:3306/harvest?useSSL=false
    username: root
    password: DEBUG
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  file: build-log
